import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import { Providers } from "../app/providers";

const montserrat = Montserrat({
	weight: ["100", "200", "300", "500", "400", "700"],
	style: ["normal", "italic"],
	subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
